# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Build Latite from source

on:
  push:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build Latite
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Upload release DLL to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Latite-Release
        path: D:\a\Latite\Latite\x64\Release\LatiteRewrite.dll

    - name: Run webhook.js
      uses: actions/setup-node@v4
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        TEST_VAR: ${{ secrets.TEST_VAR }}
      with:
        node-version: '20'
    - run: node ./webhook.js

